global:
  scrape_interval: 10s
scrape_configs:
  - job_name: spring
    static_configs:
      - targets:
          - ai-service:8080
          - vector-service:8081
          - tool-service:8082
          - edge-gateway:8083
