server.port: 8082
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer.group-id: tool-service
    consumer.properties.spring.json.trusted.packages: "*"
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management.endpoints.web.exposure.include: health,info,prometheus
mcp:
  base-url: http://localhost:8091